# Generated by Django 4.1.2 on 2022-10-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ocupied',
            field=models.BooleanField(default=False),
        ),
    ]
