# Generated by Django 4.1.2 on 2022-10-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_ocupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='hr_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='hr_ini',
            field=models.TimeField(null=True),
        ),
    ]
